workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'

stages:
  - build
  - test

build:
  stage: build
  script:
    - bash build
  artifacts:
    when: always
    reports:
      junit: results/TEST-build.xml

tests:
  stage: test
  needs: ["build"]
  script:
    - bash tests
  artifacts:
    when: always
    reports:
      junit: results/TEST-tests.xml
